Update use cases
AY2324S2-CS2103T-T10-3/tp pull request #192
Opened 2024-04-14 07:40 UTC by myang2020

2024-04-14 13:40 UTC, ChocoRagdoll reviewed
only some minor changes neccessary

2024-04-14 13:40 UTC, ChocoRagdoll commented on docs/DeveloperGuide.md
> +3. Eventy remove the participant from the event. </br>
removes

2024-04-14 13:40 UTC, ChocoRagdoll commented on docs/DeveloperGuide.md
> +1. User enters tags of the contacts or invitees he wants to export.
tags of -> flags to specify the details of

2024-04-14 13:40 UTC, ChocoRagdoll commented on docs/DeveloperGuide.md
> +2. Eventy exports the contacts or invitees along with the specified tags to a csv file </br>
exports the specified details of the contacts or invitees to a csv file

2024-04-14 14:57 UTC, Apzure submitted a review, later dismissed

2024-04-14 14:57 UTC, Apzure commented on docs/DeveloperGuide.md
> +| `* *`    | user                                       | select a specific event       | Perform actions on the desired event                                   |
The benefit for this doesn't sound concrete

2024-04-14 14:57 UTC, Apzure commented on docs/DeveloperGuide.md
> +| `* *`    | user                                       | deselect an event             | perform app-wide events                                                |
same for this

2024-04-14 14:57 UTC, Apzure commented on docs/DeveloperGuide.md
> +
Having one for each field seems excessive, could you try thinking of new ones? There can be use cases with more depth.

2024-04-14 14:57 UTC, Apzure commented on docs/DeveloperGuide.md
> +1. User selects an event or remains in global contact list.
are you allowed to have this kind of OR in use cases?

2024-04-14 17:05 UTC, nusliuyifan requested changes
You can change or just ignore  them as you like, because I'm also not sure about some of them. Please let me know when you need me to approve the pull request.

2024-04-14 17:05 UTC, nusliuyifan commented on docs/DeveloperGuide.md
> +1. User enters index of contact he wants to edit, along with the new phone number.
Oh, I just realised by contact you mean participant, can just ignore this

2024-04-14 17:05 UTC, nusliuyifan commented on docs/DeveloperGuide.md
> +A successful edit updates the person's email in both the global contact list and all the events he participates in.
maybe can use more general pronoun instead of "he", maybe "this person"

2024-04-14 17:05 UTC, nusliuyifan commented on docs/DeveloperGuide.md
> +A successful edit updates the person's email in both the global contact list and all the events he participates in.
Can ignore this if there's too much work

2024-04-15 05:10 UTC, taeewonnn requested changes
rest lgtm

2024-04-15 05:10 UTC, taeewonnn commented on docs/DeveloperGuide.md
> +2. User specific the tags he wants to filter by.
specifies

2024-04-15 05:38 UTC, taeewonnn approved these changes
lgtm

2024-04-15 06:47 UTC, merged