Implement Delete Participant Command
AY2324S2-CS2103T-T10-3/tp pull request #42
Opened 2024-03-19 16:19 UTC by ChocoRagdoll

there is a minor bug when the following command is executed: 
- `sel 1`
- `inv 1`
- `delp 1`

2024-03-19 17:54 UTC, ChocoRagdoll reviewed
no s i wrote this myself

2024-03-20 06:00 UTC, Apzure requested changes
LGTM, just a few minor changes

2024-03-20 06:00 UTC, Apzure commented on src/main/java/seedu/address/logic/commands/DeletePersonCommand.java
> +            throw new CommandException(MESSAGE_NO_SUCH_PERSON);
Test this condition

2024-03-20 06:00 UTC, Apzure commented on src/main/java/seedu/address/logic/commands/DeletePersonCommand.java
> +        }
Make the condition `(model.isAnEventSelected())` instead for readability, then reverse the statements accordingly

2024-03-20 06:48 UTC, myang2020 approved these changes

2024-03-20 06:59 UTC, Apzure approved these changes
LGTM!

2024-03-20 07:09 UTC, merged